name: desaka
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animated_icon: ^0.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^5.4.0
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get: 4.6.6
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2
  slide_digital_clock: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
